import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
import Spinner from '../components/Spinner';

const tabs=[['overview','Overview'],['categories','Categories'],['roles','Roles & Permissions'],['settings','Settings'],['audit','Audit Logs']];
export default function DashboardPage(){
  const {user}=useAuth(); const {push}=useToast(); const [params,setParams]=useSearchParams(); const tab=user?.isSuperAdmin?(params.get('panel')||'overview'):'overview';
  const [d,setD]=useState(null); const [cats,setCats]=useState([]); const [roles,setRoles]=useState([]); const [perms,setPerms]=useState([]); const [settings,setSettings]=useState([]); const [logs,setLogs]=useState([]); const [newCat,setNewCat]=useState({name:'',description:''});
  useEffect(()=>{api.dashboard().then(setD).catch(e=>push(e.message,'error'));},[]);
  useEffect(()=>{if(!user?.isSuperAdmin)return;Promise.all([api.categories(),api.roles(),api.permissions(),api.settings(),api.auditLogs()]).then(([a,b,c,s,l])=>{setCats(a);setRoles(b);setRoles(c);setPerms(c);setSettings(s);setLogs(l);}).catch(e=>push(e.message,'error'));},[user?.isSuperAdmin]);
  if(!d)return <Spinner/>;
  const go=(x)=>setParams(x==='overview'?{}:{panel:x});
  const refresh=()=>Promise.all([api.dashboard(),api.categories(),api.roles(),api.permissions(),api.settings(),api.auditLogs()]).then(([a,b,c,s,l])=>{setD(a);setCats(b);setRoles(c);setRoles(c);setPerms(c);setSettings(s);setLogs(l);});
  async function addCategory(){if(!newCat.name.trim())return;try{await api.createCategory(newCat);setNewCat({name:'',description:''});await refresh();push('Category created.')}catch(e){push(e.message,'error')}}
  async function saveSetting(row){try{await api.updateSetting({key:row.key,value:row.value});push('Setting saved.')}catch(e){push(e.message,'error')}}
  return <div><div className="page-head"><div><h1>{user?.isSuperAdmin?'Master Dashboard':'Workspace Dashboard'}</h1><div className="subtle">{user?.isSuperAdmin?'Full control center for TRIPLE-E.':'Your document management workspace.'}</div></div><div className="badge badge-teal">{user?.role?.name}</div></div>
    {user?.isSuperAdmin&&<div className="tabs">{tabs.map(([key,label])=><button key={key} className={`tab ${tab===key?'active':''}`} onClick={()=>go(key)}>{label}</button>)}</div>}
    {tab==='overview'&&<><div className="grid-4">{Object.entries(d.counts).map(([k,v])=><div key={k} className="card" style={{padding:20}}><div className="subtle" style={{fontSize:12,textTransform:'uppercase',fontWeight:900}}>{k}</div><div style={{fontSize:32,fontWeight:950,marginTop:8}}>{v}</div></div>)}</div><div className="grid-3" style={{marginTop:15}}><section className="card" style={{padding:20,gridColumn:'span 2'}}><h2>Recent activity</h2>{d.recentDocuments.map(x=><div key={x.id} className="admin-row"><div><b>{x.name}</b><div className="subtle" style={{fontSize:12}}>{x.category?.name} · {x.uploadedBy?.fullName}</div></div><span className="badge badge-teal">Document</span></div>)}</section><section className="card" style={{padding:20}}><h2>By category</h2>{d.byCategory.map(x=><div key={x.name} style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid #edf1f5'}}><span>{x.name}</span><b>{x._count.documents}</b></div>)}</section></div></>}
    {tab==='categories'&&<section className="card" style={{padding:22}}><div className="page-head"><div><h2>Categories</h2><div className="subtle">Super Admin controls the category catalogue.</div></div></div><div className="form-grid" style={{marginBottom:18}}><input placeholder="Category name" value={newCat.name} onChange={e=>setNewCat({...newCat,name:e.target.value})}/><input placeholder="Description" value={newCat.description} onChange={e=>setNewCat({...newCat,description:e.target.value})}/><button className="btn btn-primary" onClick={addCategory}>Add category</button></div><div className="admin-list">{cats.map(c=><div key={c.id} className="admin-row"><div><b>{c.name}</b><div className="subtle" style={{fontSize:12}}>{c.description}</div></div><button className="btn btn-danger btn-sm" onClick={async()=>{if(confirm(`Delete ${c.name}?`)){try{await api.deleteCategory(c.id);await refresh();push('Category deleted.')}catch(e){push(e.message,'error')}}}}>Delete</button></div>)}</div></section>}
    {tab==='roles'&&<section className="card" style={{padding:22}}><div className="page-head"><div><h2>Roles & Permission Matrix</h2><div className="subtle">Master policy layer. Use Users & Access for per-user overrides.</div></div></div>{roles.map(r=><div key={r.id} className="card" style={{padding:16,marginBottom:12,boxShadow:'none'}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',marginBottom:12}}><div><b style={{fontSize:16}}>{r.name}</b><div className="subtle" style={{fontSize:12}}>{r._count.users} users · {r.permissions.length} permissions</div></div>{r.name!=='Super Admin'&&<RoleEditor role={r} perms={perms} onSave={async(data)=>{try{await api.updateRole(r.id,data);await refresh();push('Role permissions updated.')}catch(e){push(e.message,'error')}}}/>}</div><div className="check-grid">{perms.map(p=><div key={p.id} className="check-item" style={{opacity:r.name==='Super Admin'||r.permissions.some(x=>x.permissionId===p.id)?1:.45}}>{r.name==='Super Admin'||r.permissions.some(x=>x.permissionId===p.id)?'✓':'—'} <span>{p.name}</span></div>)}</div></div>)}</section>}
    {tab==='settings'&&<section className="card" style={{padding:22}}><h2>System Settings</h2><div className="admin-list">{settings.map((s,i)=><div className="admin-row" key={s.key}><div><b>{s.key}</b><div className="subtle" style={{fontSize:12}}>Managed from UI</div></div><div style={{display:'flex',gap:8,width:'50%'}}><input value={s.value} onChange={e=>setSettings(settings.map((x,j)=>j===i?{...x,value:e.target.value}:x))}/><button className="btn btn-primary btn-sm" onClick={()=>saveSetting(s)}>Save</button></div></div>)}</div></section>}
    {tab==='audit'&&<section className="card table-wrap" style={{padding:10}}><div style={{padding:14}}><h2 style={{marginBottom:4}}>Audit Logs</h2><div className="subtle">Latest 300 recorded actions.</div></div><table className="data-table"><thead><tr><th>Time</th><th>User</th><th>Action</th><th>Entity</th><th>Entity ID</th></tr></thead><tbody>{logs.map(l=><tr key={l.id}><td>{new Date(l.createdAt).toLocaleString()}</td><td>{l.user?.fullName||'System'}</td><td><span className="badge badge-teal">{l.action}</span></td><td>{l.entity}</td><td>{l.entityId||'—'}</td></tr>)}</tbody></table></section>}
  </div>
}
function RoleEditor({role,perms,onSave}){const [open,setOpen]=useState(false);const [ids,setIds]=useState(role.permissions.map(x=>x.permissionId));const toggle=(id)=>setIds(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);return <div style={{width:'100%'}}>{open&&<div className="check-grid" style={{margin:'10px 0 12px'}}>{perms.map(p=><label key={p.id} className="check-item"><input type="checkbox" checked={ids.includes(p.id)} onChange={()=>toggle(p.id)}/><span>{p.name}</span></label>)}</div>}<button className="btn btn-light btn-sm" onClick={async()=>{if(open){await onSave({name:role.name,permissionIds:ids});setOpen(false)}else setOpen(true)}}>{open?'Save permissions':'Edit permissions'}</button></div>}
