import { useEffect, useState } from 'react';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';

export default function FoldersPage(){
  const {user}=useAuth(); const {push}=useToast(); const [folders,setFolders]=useState([]); const [categories,setCategories]=useState([]); const [form,setForm]=useState({name:'',description:'',categoryId:'',accessLevel:'PUBLIC'});
  const canManage=user?.isSuperAdmin||user?.role?.name==='Admin';
  const load=()=>api.folders().then(setFolders).catch(e=>push(e.message,'error'));
  useEffect(()=>{Promise.all([api.categories(),api.folders()]).then(([c,f])=>{setCategories(c);setFolders(f)}).catch(e=>push(e.message,'error'))},[]);
  async function create(){try{await api.createFolder(form);setForm({name:'',description:'',categoryId:'',accessLevel:'PUBLIC'});await load();push('Folder created.')}catch(e){push(e.message,'error')}}
  async function remove(id){if(!confirm('Delete this folder?'))return;try{await api.deleteFolder(id);await load();push('Folder deleted.')}catch(e){push(e.message,'error')}}
  return <div><div className="page-head"><div><h1>Folders</h1><div className="subtle">Organize operational documents by category and access.</div></div></div>{canManage&&<section className="card" style={{padding:20,marginBottom:16}}><h3>Create folder</h3><div className="form-grid"><input placeholder="Folder name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select value={form.accessLevel} onChange={e=>setForm({...form,accessLevel:e.target.value})}><option value="PUBLIC">Public to permitted users</option><option value="RESTRICTED">Restricted</option><option value="PRIVATE">Private</option></select></div><button className="btn btn-primary" style={{marginTop:14}} disabled={!form.name||!form.categoryId} onClick={create}>Create folder</button></section>}{folders.length===0?<div className="card" style={{padding:30,textAlign:'center'}}><h3>No folders visible</h3><div className="subtle">Folders restricted by the Super Admin will not appear here.</div></div>:<div className="grid-3">{folders.map(x=><div className="card" key={x.id} style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><div><div style={{fontSize:30}}>📁</div><h3 style={{margin:'8px 0 4px'}}>{x.name}</h3><div className="subtle">{x.category?.name}</div></div><span className={`badge ${x.accessLevel==='PUBLIC'?'badge-green':'badge-teal'}`}>{x.accessLevel}</span></div><p className="subtle" style={{fontSize:13,marginTop:12}}>{x.description||'No description.'}</p><div style={{fontSize:12,color:'#64748b'}}>{x._count?.documents||0} documents · {x._count?.children||0} subfolders</div>{canManage&&<button className="btn btn-danger btn-sm" style={{marginTop:14}} onClick={()=>remove(x.id)}>Delete</button>}</div>)}</div>}</div>
}
