import { useEffect,useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../context/ToastContext';
export default function UploadDocumentPage(){
  const nav=useNavigate(); const {user}=useAuth(); const {push}=useToast(); const [c,setC]=useState([]); const [f,setF]=useState([]); const [file,setFile]=useState(null); const [saving,setSaving]=useState(false); const [form,setForm]=useState({name:'',description:'',categoryId:'',folderId:'',accessLevel:'PUBLIC'});
  useEffect(()=>{Promise.all([api.categories(),api.folders()]).then(([a,b])=>{setC(a);setF(b)}).catch(e=>push(e.message,'error'))},[]);
  const canRestrict=user?.isSuperAdmin;
  async function submit(e){e.preventDefault();if(!file)return push('Please select a file.','error');setSaving(true);try{const fd=new FormData();fd.append('file',file);Object.entries(form).forEach(([k,v])=>v!==''&&fd.append(k,v));await api.uploadDocument(fd);push('Document uploaded successfully.');nav('/documents')}catch(e){push(e.message,'error')}finally{setSaving(false)}}
  return <div><div className="page-head"><div><h1>Upload document</h1><div className="subtle">Files are stored locally for development and can later be moved to online storage.</div></div></div><form onSubmit={submit} className="card" style={{padding:22,maxWidth:780}}><div className="form-grid"><label>File<input type="file" required onChange={e=>setFile(e.target.files?.[0]||null)}/></label><label>Document name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Optional"/></label><label>Category<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Select category</option>{c.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Folder<select value={form.folderId} onChange={e=>setForm({...form,folderId:e.target.value})}><option value="">Root</option>{f.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label style={{marginTop:14}}>Description<textarea rows="5" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{canRestrict?<label style={{marginTop:14}}>Access level<select value={form.accessLevel} onChange={e=>setForm({...form,accessLevel:e.target.value})}><option value="PUBLIC">PUBLIC — visible to permitted users</option><option value="RESTRICTED">RESTRICTED — controlled list</option><option value="PRIVATE">PRIVATE — owner and managers</option></select></label>:<div className="muted-box" style={{marginTop:14}}>Access control for your upload is governed by the Super Admin policy.</div>}<button className="btn btn-primary" disabled={saving} style={{marginTop:16}}>{saving?'Uploading…':'Upload document'}</button></form></div>
}
