import { useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import Modal from '../components/Modal';
import { useToast } from '../context/ToastContext';

const groups={Dashboard:['dashboard.view'],Documents:['document.view','document.create','document.update','document.delete'],Folders:['folder.view','folder.create','folder.update','folder.delete'],Users:['user.view','user.create','user.update','user.delete'],Administration:['role.manage','category.manage','settings.manage','audit.view'],Profile:['profile.update']};
export default function UsersPage(){
  const {push}=useToast(); const [users,setUsers]=useState([]); const [roles,setRoles]=useState([]); const [perms,setPerms]=useState([]); const [selected,setSelected]=useState(null); const [overrides,setOverrides]=useState({}); const [open,setOpen]=useState(false); const [form,setForm]=useState({fullName:'',email:'',phone:'',password:'',roleId:''});
  const load=async()=>{try{const [u,r,p]=await Promise.all([api.users(),api.roles(),api.permissions()]);setUsers(u);setRoles(r);setPerms(p);}catch(e){push(e.message,'error')}};
  useEffect(()=>{load()},[]);
  const permissionMap=useMemo(()=>Object.fromEntries(perms.map(p=>[p.name,p])),[perms]);
  async function selectUser(u){setSelected(u);try{const rows=await api.userPermissions(u.id);setOverrides(Object.fromEntries(rows.map(x=>[x.permission.name,x.allowed])))}catch(e){push(e.message,'error')}}
  async function saveOverrides(){try{await api.saveUserPermissions(selected.id,Object.entries(overrides).map(([name,allowed])=>({permissionId:permissionMap[name]?.id,allowed})));push('User permission overrides saved.');}catch(e){push(e.message,'error')}}
  async function create(){try{await api.createUser(form);setForm({fullName:'',email:'',phone:'',password:'',roleId:''});setOpen(false);await load();push('User created.')}catch(e){push(e.message,'error')}}
  async function toggle(u){try{await api.updateUser(u.id,{isActive:!u.isActive});await load();}catch(e){push(e.message,'error')}}
  async function del(u){if(!confirm(`Delete ${u.fullName}?`))return;try{await api.deleteUser(u.id);if(selected?.id===u.id)setSelected(null);await load();push('User deleted.')}catch(e){push(e.message,'error')}}
  return <div><div className="page-head"><div><h1>Users & Access</h1><div className="subtle">Create accounts and control access without touching code.</div></div><button className="btn btn-primary" onClick={()=>setOpen(true)}>+ Create user</button></div><div className="grid-3"><section className="card table-wrap" style={{gridColumn:'span 2'}}><table className="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div style={{fontWeight:850}}>{u.fullName}</div><div className="subtle" style={{fontSize:12}}>{u.email}</div></td><td><span className="badge badge-teal">{u.role?.name}</span></td><td><span className={`badge ${u.isActive?'badge-green':'badge-red'}`}>{u.isActive?'Active':'Inactive'}</span></td><td><div style={{display:'flex',gap:6}}><button className="btn btn-light btn-sm" onClick={()=>selectUser(u)}>Permissions</button>{!u.isSuperAdmin&&<><button className="btn btn-light btn-sm" onClick={()=>toggle(u)}>{u.isActive?'Disable':'Enable'}</button><button className="btn btn-danger btn-sm" onClick={()=>del(u)}>Delete</button></>}</div></td></tr>)}</tbody></table></section><section className="card" style={{padding:20}}><h3>Access model</h3><div className="admin-list"><div><b>Super Admin</b><div className="subtle" style={{fontSize:12}}>Master access to all system controls.</div></div><div><b>Admin</b><div className="subtle" style={{fontSize:12}}>Operational folders and documents only.</div></div><div><b>User</b><div className="subtle" style={{fontSize:12}}>Allowed content + own document management.</div></div></div></section></div>{selected&&<section className="card" style={{padding:22,marginTop:15}}><div className="page-head" style={{marginBottom:14}}><div><h2 style={{marginBottom:4}}>Permission overrides: {selected.fullName}</h2><div className="subtle">Role: {selected.role?.name}. Explicit overrides take precedence over the role.</div></div><div style={{display:'flex',gap:8}}><button className="btn btn-light" onClick={()=>setSelected(null)}>Close</button><button className="btn btn-primary" onClick={saveOverrides}>Save permissions</button></div></div><div>{Object.entries(groups).map(([g,names])=><div key={g} style={{marginBottom:18}}><h3 style={{fontSize:14}}>{g}</h3><div className="check-grid">{names.map(name=><label key={name} className="check-item"><input type="checkbox" checked={overrides[name]??false} onChange={e=>setOverrides({...overrides,[name]:e.target.checked})}/><span>{name}</span></label>)}</div></div>)}</div></section>}
    <Modal open={open} title="Create user" onClose={()=>setOpen(false)}><div style={{display:'grid',gap:12}}><label>Full name<input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>Temporary password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Role<select value={form.roleId} onChange={e=>setForm({...form,roleId:e.target.value})}><option value="">Select role</option>{roles.filter(r=>r.name!=='Super Admin').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><button className="btn btn-primary" onClick={create}>Create account</button></div></Modal></div>
}
