import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import { AuthProvider } from './context/AuthContext';
import { ToastProvider } from './context/ToastContext';

const style = document.createElement('style');
style.textContent = `
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#0f172a;background:#f6f8fb;font-synthesis:none}
*{box-sizing:border-box}body{margin:0;min-width:320px;background:#f6f8fb}button,input,select,textarea{font:inherit}button{cursor:pointer}label{display:grid;gap:7px;font-weight:700;font-size:13px}input,select,textarea{width:100%;padding:11px 12px;border:1px solid #d8dee8;border-radius:10px;background:#fff;outline:none}input:focus,select:focus,textarea:focus{border-color:#0f766e;box-shadow:0 0 0 3px #0f766e18}h1,h2,h3,p{margin-top:0}.app-shell{min-height:100vh;display:flex}.main-content{flex:1;min-width:0;padding:28px}.page-head{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:22px}.page-head h1{margin:0}.subtle{color:#64748b}.card{background:#fff;border:1px solid #e8edf3;border-radius:16px;box-shadow:0 6px 22px #0f172a0a}.btn{border:0;border-radius:10px;padding:10px 14px;font-weight:800}.btn-primary{background:#0f766e;color:#fff}.btn-danger{background:#b91c1c;color:#fff}.btn-light{background:#fff;border:1px solid #d8dee8}.btn-sm{padding:8px 10px;font-size:12px}.table-wrap{overflow:auto}.data-table{width:100%;border-collapse:collapse}.data-table th,.data-table td{text-align:left;padding:13px 14px;border-bottom:1px solid #edf1f5;white-space:nowrap}.data-table th{font-size:12px;color:#64748b;text-transform:uppercase;letter-spacing:.04em}.badge{display:inline-flex;align-items:center;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:900}.badge-green{background:#dcfce7;color:#166534}.badge-red{background:#fee2e2;color:#991b1b}.badge-teal{background:#ccfbf1;color:#115e59}.grid-4{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:15px}.grid-3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.muted-box{padding:14px 16px;border:1px dashed #cbd5e1;border-radius:12px;background:#f8fafc}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.tab{border:1px solid #d8dee8;background:#fff;border-radius:10px;padding:9px 12px;font-weight:800}.tab.active{background:#0f766e;color:#fff;border-color:#0f766e}.admin-list{display:grid;gap:10px}.admin-row{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:13px 15px;border:1px solid #e7ebf0;border-radius:12px;background:#fff}.check-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.check-item{display:flex;align-items:center;gap:9px;padding:10px;border:1px solid #e7ebf0;border-radius:10px;background:#fafcfe}.check-item input{width:auto}.side-logo{display:flex;align-items:center;gap:11px}.logo-mark{width:40px;height:40px;border-radius:12px;background:#0f766e;color:#fff;display:grid;place-items:center;font-weight:1000}.mobile-top{display:none}
@media(max-width:1050px){.grid-4{grid-template-columns:repeat(2,minmax(0,1fr))}.grid-3{grid-template-columns:repeat(2,minmax(0,1fr))}.check-grid{grid-template-columns:1fr}}
@media(max-width:760px){.app-shell{display:block}.main-content{padding:16px}.grid-4,.grid-3,.form-grid{grid-template-columns:1fr}.mobile-top{display:flex}.side-nav{position:static!important;width:100%!important;min-height:auto!important}.main-content{padding-top:12px}}
`;
document.head.appendChild(style);

ReactDOM.createRoot(document.getElementById('root')).render(<React.StrictMode><ToastProvider><AuthProvider><App /></AuthProvider></ToastProvider></React.StrictMode>);
